version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: kan-ban-app-backend-container

  db:
    image: postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistir dados do PostgreSQL
    container_name: kanban-app-container
volumes:
  postgres_data:  # Definindo o volume nomeado