version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    container_name: kanban-app-container
